<?php

return [
    // italiano
    [
        'restaurant_id' => 1,
        'name' => 'Tartare di manzo',
        'description' => 'battuta al coltello servita con bruschetta e fantasia della locanda',
        'ingredients' => 'carne',
        'price' => 12.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Degustazione di salumi selezionati',
        'description' => 'di alta qualità con gnocco fritto semi-integrales',
        'ingredients' => 'salumi',
        'price' => 15.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Degustazione di formaggi tipici della Lessinia',
        'description' => 'con mostarde e marmellate di produzione',
        'ingredients' => 'formaggio',
        'price' => 16.00,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Tartare di gamberi rossi della Sicilia',
        'description' => 'e concassè i confit su cuore di straccitella e prosciutto crudo croccante',
        'ingredients' => 'gamberi',
        'price' => 14.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Tortellini di valeggio al burro fuso',
        'description' => 'tortellini fatti a mano come vuole la tradizione',
        'ingredients' => 'farina, uova',
        'price' => 11.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Spaghetti i grano duro di Gragnano',
        'description' => 'al profumo delicato di mare (cozze, vongole, eppioline e calamari)',
        'ingredients' => 'farina, sale',
        'price' => 13.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Tagliata di tonno fresco',
        'description' => 'scottato in crosta di sesamo e salsa di basilico',
        'ingredients' => 'tonno, basilico, sesamo',
        'price' => 20.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Fritto misto di pesce',
        'description' => 'con tempura di verdure fresche e salsa lime e zenzero',
        'ingredients' => 'misto pesce',
        'price' => 22.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Galletto vallespuga ai ferri',
        'description' => '500gr, con patatine fritte rustiche con la buccia',
        'ingredients' => 'galletto, patate',
        'price' => 15.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Insalatona bufala',
        'description' => 'insalata mista',
        'ingredients' => 'Bufala campana, olivenere, insalata gentile, radicchio, carote',
        'price' => 13.00,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 1,
        'name' => 'Insalatona estiva',
        'description' => 'insalata mista',
        'ingredients' => 'Lattuga, olive nere, pomodorini, uova, patate lesse, trancetti di tonno, basilico',
        'price' => 12.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // giappone
    [
        'restaurant_id' => 2,
        'name' => 'Involtini ai Gamberi',
        'description' => 'Involtini ai Gamberi',
        'ingredients' => 'farina e gamberi',
        'price' => 2,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Nuvolette di Drago',
        'description' => 'Il prodotto contiene crostacei e prodotti a base di crostacei e i loro derivati',
        'ingredients' => 'gamberi',
        'price' => 1.80,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Gyoza',
        'description' => 'Ravioli alla Griglia',
        'ingredients' => 'farina, carne e verza',
        'price' => 3,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Alghe Fritte',
        'description' => 'Alghe Fritte',
        'ingredients' => 'Alghe',
        'price' => 1.80,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Riso alla Cantonese',
        'description' => 'Informazione: Il prodotto contiene uova e prodotti a base di uova',
        'ingredients' => 'riso, piselli, prosciutto cotto e uova',
        'price' => 3,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Sashimi Misto',
        'description' => '9 pezzi di sashimi di salmone, tonno e pesce bianco',
        'ingredients' => 'salmone, tonno e pesce bianco',
        'price' => 9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Nigiri Shake',
        'description' => 'oblunga di riso, al di sopra della quale viene disposto il pesce',
        'ingredients' => 'salmone, riso ',
        'price' => 3,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Nigiri Amaebi',
        'description' => 'oblunga di riso, al di sopra della quale viene disposto il pesce',
        'ingredients' => 'gambero rosso, riso',
        'price' => 4,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Gunkan Ikura',
        'description' => 'barca di riso, al di sopra della quale viene disposto il pesce',
        'ingredients' => 'uova di salmone, alga, riso',
        'price' => 5.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 2,
        'name' => 'Gunkan Yasai Amaebi',
        'description' => 'barca di riso, al di sopra della quale viene disposto il pesce',
        'ingredients' => 'gambero rosso e avocado',
        'price' => 5.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // messicano
    [
        'restaurant_id' => 3,
        'name' => 'Burrito philadelphia edition',
        'description' => 'Burrito con Philadelphia, il formaggio dal gusto unico e inimitabile.',
        'ingredients' => 'rucola, philadelphia, petto di pollo grigliato',
        'price' => 9.60,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Chimichangas',
        'description' => 'Due fagottini di tortilla ripiene di carne',
        'ingredients' => 'manzo, peperoni, formaggio, salsa ranch, riso messicano',
        'price' => 8.80,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Flautas de Tinga ',
        'description' => 'Due tortillas di farina fritte e servite con insalata mista, pico de galo e riso',
        'ingredients' => 'farina, pollo, chorizo',
        'price' => 7.60,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Panuchos de Tinga',
        'description' => 'Due tortillas di farina impanate e fritte, servite calde con carne di pollo sfilettata, chorizo e pomodoro. Il tutto accompagnato da insalata mista, pico de gala e formaggio.',
        'ingredients' => 'pollo, chorizo, formaggio, verdure',
        'price' => 10.20,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Burrito de Frijoles y Chorizo',
        'description' => 'Grossa tortilla di farina riempita con fagioli e chorizo. Servita con guacamole, sour cream e riso messicano.',
        'ingredients' => 'farina, fagioli, chorizo, avocado, riso',
        'price' => 10.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Tostada Vegetariana',
        'description' => 'Due tortillas di farina impanate e fritte, ricoperte di peperoni, fagioli e formaggio. Servite con insalata verde e pomodoro a cubetti.',
        'ingredients' => 'farina, verdure, formaggio',
        'price' => 10.20,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Fajitas Vegetale',
        'description' => 'Carote, zucchine e peperoni a striscioline. Marinati e serviti con riso della cantina, rondelle di pannocchia grigliata e formaggio fuso, con tortillas calde.',
        'ingredients' => 'riso, tortillas, verdure, formaggio',
        'price' => 11.50,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Pulpo y Papas',
        'description' => 'Deliziosi pezzetti di polipo cucinati con spezie e patate. Serviti con tortillas, riso della cantina e pico de galo.',
        'ingredients' => 'polipo, patate, tortillas, riso',
        'price' => 11.90,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Pescado Frito y Camarones',
        'description' => 'Un trionfo per chi ama il pesce fritto: delizioso filetto di pesce panato, cornados, anelli di calamaro e gamberi. Il tutto dorato e fritto, accompagnato da squisita salsa rosa.',
        'ingredients' => 'pesce misto, salsa rosa',
        'price' => 16.10,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Tacos de Camarones',
        'description' => 'Due tortillas tostate ricoperte di salsa rosada con gamberi fritti, pico de galo, insalata e radicchio.',
        'ingredients' => 'tortillas, gamberi, verdura',
        'price' => 15.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 3,
        'name' => 'Sincronizada',
        'description' => 'Grossa tortilla di farina cotta alla piastra e riempita con formaggio e prosciutto cotto. Servita con patate fritte.',
        'ingredients' => 'tortilla, formaggio, prosciutto, patate',
        'price' => 8.70,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // pizzeria
    [
        'restaurant_id' => 4,
        'name' => 'Margherita',
        'description' => 'l classico per eccellenza, la nostra pizza più amata.',
        'ingredients' => 'Pomodoro, mozzarella filante, sale e olio',
        'price' => 7.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Patate e salsiccia',
        'description' => 'Un\'esplosione di sapori per una ricetta ricca e gustosa. ',
        'ingredients' => 'Mozzarella, patate, salsiccia',
        'price' => 8.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Diavola',
        'description' => 'Dalla leggera piccantezza, ma di grande soddisfazione',
        'ingredients' => 'Salame piccante e mozzarella',
        'price' => 8,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Mortadella, stracciatella e pistacchi',
        'description' => 'Per un piacere fresco e cremoso',
        'ingredients' => 'Mortadella, stracciatella e pistacchi',
        'price' => 8.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Pomodorini e alici',
        'description' => 'Pomodorini e alici',
        'ingredients' => 'Pomodorini e alici',
        'price' => 9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Cacio e pepe',
        'description' => 'Un nostro omaggio alla tradizione gastronomica, romana',
        'ingredients' => 'Cacio e pepe',
        'price' => 8.50,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Funghi e quattro formaggi',
        'description' => 'Uno strato di funghi tagliati sottilmente incontra una salsa saporita ai 4 formaggi.',
        'ingredients' => 'Funghi e quattro formaggi',
        'price' => 8,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Zucchine e Bufala',
        'description' => 'Zucchine tagliate a rondelle e saporita bufala si incontrano per una pizza in teglia dal gusto fresco e piacevole',
        'ingredients' => 'Zucchine e Bufala',
        'price' => 8,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Fiori di zucca e bacon o prosciutto cotto',
        'description' => 'A seconda della disponibilità della cucina',
        'ingredients' => 'Fiori di zucca e bacon o prosciutto cotto',
        'price' => 8,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 4,
        'name' => 'Funghi rossa',
        'description' => 'Funghi rossa',
        'ingredients' => 'Funghi, pomodoro',
        'price' => 7,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    // greco
    [
        'restaurant_id' => 7,
        'name' => 'Moussaka',
        'description' => 'Moussaka è un piatto tipico greco a base di melanzane, carne macinata e bechamel.',
        'ingredients' => 'melanzane, carne macinata, patate, pomodoro, cipolle, aglio, olio d\'oliva, pangrattato, parmigiano, latte, farina, burro',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Souvlaki',
        'description' => 'Souvlaki è una tipica specialità greca a base di carne marinata e grigliata, servita su uno spiedino.',
        'ingredients' => 'carne di maiale o pollo, olio d\'oliva, aceto di vino bianco, aglio, origano, limone, sale, pepe',
        'price' => 8.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Tzatziki',
        'description' => 'Tzatziki è una salsa a base di yogurt, cetrioli e aglio, tipica della cucina greca.',
        'ingredients' => 'yogurt, cetrioli, aglio, olio d\'oliva, sale',
        'price' => 3.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Spanakopita',
        'description' => 'Spanakopita è un piatto greco a base di spinaci e formaggio feta, avvolto in una sfoglia di pasta fillo.',
        'ingredients' => 'spinaci, feta, uova, cipolle, aglio, erbe aromatiche, olio d\'oliva, pasta fillo',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Dolmades',
        'description' => 'Dolmades sono involtini di foglie di vite ripieni di riso e spezie, tipici della cucina greca.',
        'ingredients' => 'foglie di vite, riso, cipolle, aglio, prezzemolo, menta, succo di limone, olio d\'oliva',
        'price' => 7.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Horiatiki',
        'description' => 'Horiatiki è una tipica insalata greca a base di pomodori, cetrioli, cipolle, peperoni, olive e formaggio feta.',
        'ingredients' => 'pomodori, cetrioli, cipolle, peperoni, olive, formaggio feta, origano, sale, pepe, olio d\'oliva',
        'price' => 7.9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Saganaki',
        'description' => 'Saganaki è un piatto greco a base di formaggio feta o kefalotyri fuso e fritto in padella.',
        'ingredients' => 'formaggio feta o kefalotyri, olio d\'oliva, limone',
        'price' => 8.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kolokithokeftedes',
        'description' => 'Kolokithokeftedes sono polpette di zucchine grattugiate, formaggio feta e spezie, tipiche della cucina greca.',
        'ingredients' => 'zucchine, formaggio feta, uova, pangrattato, cipolle, aglio, erbe aromatiche, sale, pepe, olio d\'oliva',
        'price' => 9.9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Gyros',
        'description' => 'Gyros è un piatto greco a base di carne di maiale marinata e arrostita, servita in un panino con verdure e salsa tzatziki.',
        'ingredients' => 'carne di maiale, olio d\'oliva, aglio, origano, peperoncino, verdure miste, pane pita, tzatziki',
        'price' => 10.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Fava',
        'description' => 'Fava è una crema di fagioli gialli servita come antipasto o contorno, tipica della cucina greca.',
        'ingredients' => 'fagioli gialli, cipolle, aglio, limone, olio d\'oliva, origano',
        'price' => 6.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    // indiano
    [
        'restaurant_id' => 9,
        'name' => 'Samosa',
        'description' => 'Samosa è un antipasto indiano a forma di triangolo ripieno di patate, piselli, cipolle e spezie, fritto in olio.',
        'ingredients' => 'farina, patate, piselli, cipolle, spezie indiane, olio di semi di arachidi, sale',
        'price' => 4.9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Tandoori Chicken',
        'description' => 'Il pollo tandoori è un piatto indiano di pollo marinato con spezie e cotto in un forno tandoor, servito con chutney.',
        'ingredients' => 'petto di pollo, yogurt, zenzero, aglio, curcuma, paprika, pepe di cayenna, cumino, garam masala, sale',
        'price' => 10.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Chana Masala',
        'description' => 'Chana masala è un piatto vegetariano indiano a base di ceci speziati, pomodori, cipolle e coriandolo.',
        'ingredients' => 'ceci, pomodori, cipolle, zenzero, aglio, peperoncino, garam masala, coriandolo, olio di semi di arachidi',
        'price' => 9.9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Butter Chicken',
        'description' => 'Il pollo al burro, o butter chicken, è un piatto indiano di pollo cotto in una salsa di pomodoro, panna e spezie.',
        'ingredients' => 'petto di pollo, pomodori, cipolle, aglio, zenzero, panna, burro, paprika, cumino, garam masala, coriandolo, sale',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Biryani',
        'description' => 'Il biryani è un piatto indiano a base di riso aromatizzato con spezie e carne, verdure o uova.',
        'ingredients' => 'riso basmati, carne di pollo, agnello o manzo, cipolle, zenzero, aglio, pomodori, spezie indiane, yogurt, coriandolo, menta',
        'price' => 13.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Sag Paneer',
        'description' => 'Sag paneer è un piatto vegetariano indiano a base di spinaci freschi e formaggio paneer.',
        'ingredients' => 'spinaci freschi, formaggio paneer, pomodori, cipolle, aglio, zenzero, garam masala, peperoncino, olio di semi di arachidi, sale',
        'price' => 10,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Aloo Gobi',
        'description' => 'Aloo gobi è un piatto vegetariano indiano a base di patate, cavolfiore e spezie.',
        'ingredients' => 'patate, cavolfiore, cipolle, zenzero, aglio, pomodori, cumino, curcuma, garam masala, peperoncino, coriandolo, olio di semi di arachidi, sale',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Vindaloo',
        'description' => 'Il vindaloo è un piatto indiano piccante a base di carne marinata in una salsa di aceto e spezie.',
        'ingredients' => 'carne di maiale o agnello, aceto, peperoncino, zenzero, aglio, cumino, coriandolo, pepe di Caienna, garam masala, olio di semi di arachidi, sale',
        'price' => 12.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Tikka Masala',
        'description' => 'Il pollo tikka masala è un piatto indiano di pollo marinato in yogurt e spezie, cotto in una salsa di pomodoro e panna.',
        'ingredients' => 'petto di pollo, yogurt, zenzero, aglio, cumino, paprika, garam masala, pomodori, panna, burro, coriandolo, menta, sale',
        'price' => 13.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 9,
        'name' => 'Raita',
        'description' => 'Il raita è un contorno indiano a base di yogurt, cetrioli e spezie, servito freddo.',
        'ingredients' => 'yogurt, cetrioli, cipolle, pomodori, zenzero, coriandolo, menta, sale',
        'price' => 5.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    // turco
    [
        'restaurant_id' => 10,
        'name' => 'Kebab di agnello',
        'description' => 'Il kebab di agnello è un piatto turco a base di carne di agnello marinata e speziata.',
        'ingredients' => 'carne di agnello, yogurt, paprika, cumino, aglio, menta, olio d\'oliva, sale',
        'price' => 12.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Köfte',
        'description' => 'Il köfte è un piatto turco a base di polpette di carne macinata e spezie.',
        'ingredients' => 'carne macinata, pane grattugiato, uova, cipolle, aglio, paprika, cumino, peperoncino, prezzemolo, menta, olio d\'oliva, sale',
        'price' => 10,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Doner Kebab',
        'description' => 'Il doner kebab è un piatto turco a base di carne di maiale, agnello o pollo cotta su uno spiedo verticale e servita in un panino o in un piatto.',
        'ingredients' => 'carne di maiale, agnello o pollo, yogurt, aglio, paprika, cumino, menta, olio d\'oliva, sale',
        'price' => 8.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Lahmacun',
        'description' => 'Il lahmacun è una pizza turca sottile e croccante, condita con carne macinata, pomodori, peperoni e spezie.',
        'ingredients' => 'farina, lievito, carne macinata, pomodori, peperoni, cipolle, aglio, paprika, cumino, peperoncino, prezzemolo, menta, olio d\'oliva, sale',
        'price' => 7.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Hummus',
        'description' => 'L\'hummus è una salsa turca a base di ceci, tahini, aglio e limone.',
        'ingredients' => 'ceci, tahini, aglio, limone, olio d\'oliva, sale',
        'price' => 5.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Baklava',
        'description' => 'La baklava è un dolce turco a base di sfoglia di pasta fillo, noci e sciroppo di miele.',
        'ingredients' => 'pasta fillo, noci, zucchero, sciroppo di miele',
        'price' => 4.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Simit',
        'description' => 'Il simit è un tipico pane turco a forma di ciambella, ricoperto di semi di sesamo.',
        'ingredients' => 'farina, lievito, zucchero, sale, semi di sesamo',
        'price' => 2.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Menemen',
        'description' => 'Il menemen è una salsa turca a base di uova, pomodori e peperoni, spesso accompagnata da pane tostato.',
        'ingredients' => 'uova, pomodori, peperoni, aglio, cipolle, prezzemolo, olio d\'oliva, sale',
        'price' => 6.9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Pilav',
        'description' => 'Il pilav è un piatto turco a base di riso, spesso accompagnato da verdure e carne.',
        'ingredients' => 'riso, verdure miste, carne (opzionale), brodo di carne (opzionale), olio d\'oliva, sale',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 10,
        'name' => 'Iskender Kebab',
        'description' => 'L\'iskender kebab è un piatto turco a base di carne di agnello servita su una base di pane pita, con salsa di pomodoro e yogurt.',
        'ingredients' => 'carne di agnello, pane pita, pomodori, yogurt, aglio, menta, burro, sale',
        'price' => 14.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // poke
    [
        'restaurant_id' => 5,
        'name' => 'Hawaiian Pokè',
        'description' => 'riso sushi, salmone, avocado, edamame, semi di sesamo e salsa di soia',
        'ingredients' => 'riso sushi, salmone, avocado, edamame, semi di sesamo e salsa di soia',
        'price' => 10.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],

    [
        'restaurant_id' => 5,
        'name' => 'Pokè di Salmone e Gamberi',
        'description' => 'riso sushi, salmone, gamberi, avocado, edamame, semi di sesamo e salsa di soia',
        'ingredients' => 'riso sushi, salmone, gamberi, avocado, edamame, semi di sesamo e salsa di soia',
        'price' => 12.9,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],

    [
        'restaurant_id' => 5,
        'name' => 'Pokè di Tonno',
        'description' => 'riso sushi, tonno, avocado, edamame, semi di sesamo e salsa di soia',
        'ingredients' => 'riso sushi, tonno, avocado, edamame, semi di sesamo e salsa di soia',
        'price' => 11.90,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],

    [
        'restaurant_id' => 5,
        'name' => 'Pokè Vegetariano',
        'description' => 'riso sushi, avocado, edamame, carote, cetrioli, semi di sesamo e salsa di soia',
        'ingredients' => 'riso sushi, avocado, edamame, carote, cetrioli, semi di sesamo e salsa di soia',
        'price' => 9,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],

    [
        'restaurant_id' => 5,
        'name' => 'Pokè di Pollo Teriyaki',
        'description' => 'riso sushi, pollo teriyaki, avocado, edamame, semi di sesamo e salsa di soia',
        'ingredients' => 'riso sushi, pollo teriyaki, avocado, edamame, semi di sesamo e salsa di soia',
        'price' => 10.90,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],

    [
        'restaurant_id' => 5,
        'name' => 'Pokè di Salmone e Avocado',
        'description' => 'riso sushi, salmone, avocado, edamame, semi di sesamo, cipolla e salsa di soia',
        'ingredients' => 'riso sushi, salmone, avocado, edamame, semi di sesamo, cipolla e salsa di soia',
        'price' => 12.90,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Poke di Tonno e Mango',
        'description' => 'Riso sushi, tonno fresco, mango, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'ingredients' => 'Riso sushi, tonno fresco, mango, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'price' => 13.90,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Poke Vegano',
        'description' => 'Riso sushi, tofu, avocado, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'ingredients' => 'Riso sushi, tofu, avocado, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'price' => 11.90,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 5,
        'name' => 'Poke di Gamberi e Avocado',
        'description' => 'Riso sushi, gamberi freschi, avocado, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'ingredients' => 'Riso sushi, gamberi freschi, avocado, cetrioli, edamame, semi di sesamo, cipolla rossa e salsa di soia',
        'price' => 14.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],

    // bbq\hamburger
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger Classico',
        'description' => 'Hamburger di manzo 100% italiano, pane fresco, insalata, pomodoro, cipolla e ketchup.',
        'ingredients' => 'carne di manzo, pane, insalata, pomodoro, cipolla, ketchup',
        'price' => 8.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger Vegetariano',
        'description' => 'Hamburger di verdure fresche, pane integrale, formaggio, insalata e maionese.',
        'ingredients' => 'verdure fresche, pane integrale, formaggio, insalata, maionese',
        'price' => 7.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger con Bacon',
        'description' => 'Hamburger di manzo 100% italiano, bacon croccante, formaggio, insalata, pomodoro e maionese.',
        'ingredients' => 'carne di manzo, bacon, formaggio, insalata, pomodoro, maionese',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger con Funghi',
        'description' => 'Hamburger di manzo 100% italiano, funghi freschi, formaggio, insalata, pomodoro e maionese.',
        'ingredients' => 'carne di manzo, funghi freschi, formaggio, insalata, pomodoro, maionese',
        'price' => 10.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger con Guacamole',
        'description' => 'Hamburger di manzo 100% italiano, guacamole fatto in casa, insalata e pomodoro.',
        'ingredients' => 'carne di manzo, guacamole, insalata, pomodoro',
        'price' => 11.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hot Dog',
        'description' => 'Pancetta di maiale, wurstel, senape e ketchup su un panino morbido.',
        'ingredients' => 'pancetta di maiale, wurstel, senape, ketchup, panino',
        'price' => 6.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Pollo alla Griglia',
        'description' => 'Petto di pollo marinato e grigliato con patate fritte e insalata.',
        'ingredients' => 'petto di pollo, marinata, patate fritte, insalata',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Brisket Affumicato',
        'description' => 'Petto di manzo affumicato a bassa temperatura con salsa BBQ, patate al forno e verdure.',
        'ingredients' => 'petto di manzo, affumicatura, salsa BBQ, patate al forno, verdure',
        'price' => 15.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Alette di Pollo',
        'description' => 'Alette di pollo fritte con salsa BBQ e patatine fritte.',
        'ingredients' => 'alette di pollo, frittura, salsa BBQ, patatine fritte',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Hamburger con Jalapeños',
        'description' => 'Hamburger di manzo 100% italiano con jalapeños, formaggio, insalata, pomodoro e maionese.',
        'ingredients' => 'carne di manzo, jalapeños, formaggio, insalata, pomodoro, maionese',
        'price' => 11.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 11,
        'name' => 'Costolette di Maiale',
        'description' => 'Costolette di maiale alla griglia con salsa BBQ, patate al forno e verdure.',
        'ingredients' => 'costolette di maiale, grigliatura, salsa BBQ, patate al forno, verdure',
        'price' => 14.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // africano
    [
        'restaurant_id' => 12,
        'name' => 'Couscous di Verdure',
        'description' => 'Couscous con verdure miste in salsa di pomodoro e spezie.',
        'ingredients' => 'couscous, verdure, salsa di pomodoro, spezie',
        'price' => 10.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Pollo in Salsa di Arachidi',
        'description' => 'Pollo al curry in salsa di arachidi, servito con riso basmati.',
        'ingredients' => 'pollo, curry, arachidi, riso basmati',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Zuppa di Fagioli',
        'description' => 'Zuppa di fagioli con pomodori, cipolle e spezie.',
        'ingredients' => 'fagioli, pomodori, cipolle, spezie',
        'price' => 8,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Bobotie',
        'description' => 'Un piatto sudafricano composto da carne macinata, pane, uova e spezie, servito con chutney di frutta.',
        'ingredients' => 'carne macinata, pane, uova, spezie, chutney di frutta',
        'price' => 13,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Jollof Rice',
        'description' => 'Riso speziato con pomodori, peperoni, cipolle e pollo.',
        'ingredients' => 'riso, pomodori, peperoni, cipolle, pollo',
        'price' => 11.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Akara',
        'description' => 'Polpette di fagioli neri fritte, servite con salsa di pomodoro e peperoncino.',
        'ingredients' => 'fagioli neri, salsa di pomodoro, peperoncino',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Yassa di Pollo',
        'description' => 'Pollo marinato in una salsa di cipolle, limone e spezie, servito con riso.',
        'ingredients' => 'pollo, cipolle, limone, spezie, riso',
        'price' => 13.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Fufu e Zuppa di Arachidi',
        'description' => 'Purè di fufu con zuppa di arachidi, carne e verdure.',
        'ingredients' => 'fufu, arachidi, carne, verdure',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Kelewele',
        'description' => 'Banane fritte con zenzero e peperoncino.',
        'ingredients' => 'banane, zenzero, peperoncino',
        'price' => 8.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Bunny Chow',
        'description' => 'Un piatto sudafricano composto da un pane scavato e riempito con curry di carne o verdure.',
        'ingredients' => 'pane, curry, carne o verdure',
        'price' => 11.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 12,
        'name' => 'Nyama Choma',
        'description' => 'Arrosti di carne di capra, agnello o manzo marinati in spezie, serviti con ugali (polenta di mais).',
        'ingredients' => 'carne di capra, agnello o manzo, spezie, ugali',
        'price' =>  14.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    // fastfood
    [
        'restaurant_id' => 13,
        'name' => 'Margherita',
        'description' => 'Pizza con pomodoro, mozzarella e basilico.',
        'ingredients' => 'pomodoro, mozzarella, basilico',
        'price' => 8.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Diavola',
        'description' => 'Pizza con pomodoro, mozzarella, salame piccante e peperoncino.',
        'ingredients' => 'pomodoro, mozzarella, salame piccante, peperoncino',
        'price' => 9.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Calzone',
        'description' => 'Pizza chiusa a metà con pomodoro, mozzarella, prosciutto cotto e funghi.',
        'ingredients' => 'pomodoro, mozzarella, prosciutto cotto, funghi',
        'price' => 10.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Focaccia',
        'description' => 'Focaccia con pomodorini, mozzarella, origano e olio d\'oliva.',
        'ingredients' => 'pomodorini, mozzarella, origano, olio d\'oliva',
        'price' => 6.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Panzerotto',
        'description' => 'Impasto di pizza ripieno con pomodoro, mozzarella e prosciutto cotto.',
        'ingredients' => 'impasto di pizza, pomodoro, mozzarella, prosciutto cotto',
        'price' => 8.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Hamburger classico',
        'description' => 'Pane con carne di manzo, lattuga, pomodoro e salsa speciale.',
        'ingredients' => 'pane, carne di manzo, lattuga, pomodoro, salsa speciale',
        'price' => 6.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Cheeseburger',
        'description' => 'Pane con carne di manzo, formaggio, lattuga, pomodoro e salsa speciale.',
        'ingredients' => 'pane, carne di manzo, formaggio, lattuga, pomodoro, salsa speciale',
        'price' => 7.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Chicken nuggets',
        'description' => 'Bocconcini di pollo panati, fritti e croccanti.',
        'ingredients' => 'pollo, pangrattato, uova, sale',
        'price' => 5.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Hot dog',
        'description' => 'Pagnotta con salsiccia, ketchup, senape e cipolle.',
        'ingredients' => 'pagnotta, salsiccia, ketchup, senape, cipolle',
        'price' => 6.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 13,
        'name' => 'Patatine fritte',
        'description' => 'Patate tagliate a bastoncini e fritte croccanti.',
        'ingredients' => 'patate, olio, sale',
        'price' => 3.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    // kebab
    [
        'restaurant_id' => 7,
        'name' => 'Pollo kebab',
        'description' => 'Filetto di pollo marinato, grigliato e servito in una pita con verdure fresche e salsa tzatziki.',
        'ingredients' => 'Filetto di pollo, verdure fresche, salsa tzatziki, pita',
        'price' => 7.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab di agnello',
        'description' => 'Spezzatino di agnello marinato, grigliato e servito in una pita con verdure fresche e salsa allo yogurt.',
        'ingredients' => 'Spezzatino di agnello, verdure fresche, salsa allo yogurt, pita',
        'price' => 8.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Falafel kebab',
        'description' => 'Polpettine di ceci fritte e servite in una pita con verdure fresche e salsa tahini.',
        'ingredients' => 'Polpettine di ceci, verdure fresche, salsa tahini, pita',
        'price' => 7.00,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab di agnello',
        'description' => 'Carne di agnello speziata servita su una pita di pane arrotolata con lattuga, pomodori e cipolla',
        'ingredients' => 'Carne di agnello, pita di pane, lattuga, pomodori, cipolla, spezie',
        'price' => 6.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,

        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab vegetariano',
        'description' => 'Falafel croccanti serviti su una pita di pane arrotolata con lattuga, pomodori, cipolla e salsa tzatziki',
        'ingredients' => 'Falafel, pita di pane, lattuga, pomodori, cipolla, salsa tzatziki',
        'price' => 5.50,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,

        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab vegetariano',
        'description' => 'Falafel croccanti serviti su una pita di pane arrotolata con lattuga, pomodori, cipolla e salsa tzatziki',
        'ingredients' => 'Falafel, pita di pane, lattuga, pomodori, cipolla, salsa tzatziki',
        'price' => 5.50,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,

        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab di pollo piccante',
        'description' => 'Pollo speziato servito su una pita di pane arrotolata con lattuga, pomodori e salsa piccante',
        'ingredients' => 'Carne di pollo, pita di pane, lattuga, pomodori, salsa piccante, spezie',
        'price' => 6.00,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,

        'image_path' => '',
    ],
    [
        'restaurant_id' => 7,
        'name' => 'Kebab di tacchino',
        'description' => 'Carne di tacchino marinata servita su una pita di pane arrotolata con lattuga, pomodori e cipolla',
        'ingredients' => 'Carne di tacchino, pita di pane, lattuga, pomodori, cipolla, marinatura',
        'price' => 6.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,

        'image_path' => '',
    ],
    // hamburger
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger al tartufo',
        'description' => 'Carne di manzo 100% di prima scelta con tartufo nero, formaggio cheddar, lattuga e salsa segreta.',
        'ingredients' => 'carne di manzo, tartufo nero, formaggio cheddar, lattuga, salsa segreta',
        'price' => 15.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger alla bresaola',
        'description' => 'Hamburger di bresaola, cipolla caramellata, formaggio brie, pomodoro e rucola.',
        'ingredients' => 'bresaola, cipolla caramellata, formaggio brie, pomodoro, rucola',
        'price' => 14.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger al formaggio di capra',
        'description' => 'Carne di manzo 100% di prima scelta con formaggio di capra, cipolle caramellate e rucola.',
        'ingredients' => 'carne di manzo, formaggio di capra, cipolle caramellate, rucola',
        'price' => 16.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger al salmone',
        'description' => 'Hamburger di salmone, lattuga, pomodoro, avocado e maionese alla senape.',
        'ingredients' => 'salmone, lattuga, pomodoro, avocado, maionese alla senape',
        'price' => 17.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger vegano',
        'description' => 'Hamburger di quinoa, fagioli neri, avocado, pomodoro e cipolla rossa.',
        'ingredients' => 'quinoa, fagioli neri, avocado, pomodoro, cipolla rossa',
        'price' => 12.5,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 1,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger di agnello',
        'description' => 'Hamburger di agnello, formaggio feta, cetriolo, lattuga e tzatziki.',
        'ingredients' => 'agnello, formaggio feta, cetriolo, lattuga, tzatziki',
        'price' => 16.5,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger di Manzo',
        'description' => 'Pane ai semi di sesamo, hamburger di manzo, formaggio cheddar, lattuga, pomodoro, cipolla rossa, ketchup e maionese.',
        'ingredients' => 'manzo, formaggio cheddar, lattuga, pomodoro, cipolla rossa, ketchup, maionese',
        'price' => 12,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger "Bacon e Formaggio"',
        'description' => 'Pane ai cereali, hamburger di manzo, formaggio gouda, bacon croccante, lattuga, pomodoro e maionese al peperoncino.',
        'ingredients' => 'manzo, formaggio gouda, bacon, lattuga, pomodoro, maionese al peperoncino',
        'price' => 13.50,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger "Gourmet"',
        'description' => 'Pane alla curcuma, hamburger di manzo wagyu, formaggio brie, rucola, cipolla caramellata e maionese alla senape.',
        'ingredients' => 'manzo wagyu, formaggio brie, rucola, cipolla caramellata, maionese alla senape',
        'price' => 18,
        'visible' => 1,
        'vegetarian' => 0,
        'vegan' => 0,
        'image_path' => '',
    ],
    [
        'restaurant_id' => 6,
        'name' => 'Hamburger "Vegetariano"',
        'description' => 'Pane integrale, hamburger vegetariano di legumi e verdure, formaggio di capra, zucchine grigliate, pomodori freschi e salsa allo yogurt e menta.',
        'ingredients' => 'hamburger vegetariano di legumi e verdure, formaggio di capra, zucchine grigliate, pomodori freschi, salsa allo yogurt e menta',
        'price' => 10.50,
        'visible' => 1,
        'vegetarian' => 1,
        'vegan' => 0,
        'image_path' => '',
    ],
];
